spring:
  profiles:
    include:
      - oauth
      - real-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
  session:
    store-type: jdbc