server:
  port: 8083
spring:
  profiles:
    include:
      - oauth
      - real-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
  session:
    store-type: jdbc