server:
  port: 8081
  servlet:
    encoding:
      force: true

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL47Dialect
        dialect.storage_engine: innodb

    show_sql: true


  session:
    store-type: jdbc

  h2:
    console:
      enabled: true # h2 웹 콘솔 활성화

  profiles:
    include: oauth


  datasource:
    hikari:
      username: sa
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL



