spring:
  profiles:
    include: oauth

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: 'jdbc:h2:mem:testdb'
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  sql:
    init:
      data-locations: classpath:data-h2.sql

  session:
    store-type: jdbc

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.type: trace